module(name = "svetoch_bazel_lib")

###########
# Bazel
###########
http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_file = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")

bazel_dep(name = "buildifier_prebuilt", version = "8.5.1")
bazel_dep(name = "aspect_bazel_lib", version = "2.22.5")

bazel_lib_toolchains = use_extension("@aspect_bazel_lib//lib:extensions.bzl", "toolchains")
use_repo(bazel_lib_toolchains, "zstd_toolchains")

bazel_dep(name = "rules_multirun", version = "0.10.0")

######################
# Binary tools support
######################
bazel_dep(name = "rules_bin_tools")
git_override(
    module_name = "rules_bin_tools",
    commit = "d3fefc59031fe28fcc41918f8e9df752c58c3c49",
    remote = "https://github.com/ggramal/rules_bin_tools",
)

tools = use_extension("@rules_bin_tools//tools:extensions.bzl", "tools")
tools.download(
    helm_version = "v3.18.4",
    suffix = "exec",
)
use_repo(tools, "helm_exec")

######################
# Terraform support
######################

bazel_dep(name = "rules_tf")
git_override(
    module_name = "rules_tf",
    commit = "841d00ec6a9d619e278c6adf37b343bda7f1a554",
    remote = "https://github.com/ggramal/rules_tf",
)

tf = use_extension("@rules_tf//tf:extensions.bzl", "tf")
tf.toolchain(
    name = "svetoch_bazel_lib_tf_executable",
    version = "1.14.4",
)
use_repo(tf, "svetoch_bazel_lib_tf_executable")

register_toolchains(
    "@svetoch_bazel_lib_tf_executable//:all",
)

load_file = use_extension("@svetoch_bazel_lib//tools:extensions.bzl", "load_file")
load_file.json(
    name = "svetoch_bazel_lib_tfvars",
    src = "@svetoch_bazel_lib//:terraform.tfvars.json",
    variable_name = "tfvars",
)
use_repo(load_file, "svetoch_bazel_lib_tfvars")

###################
# Container support
###################

bazel_dep(name = "rules_oci", version = "2.3.0")
bazel_dep(name = "rules_distroless", version = "0.8.0")

oci = use_extension("@rules_oci//oci:extensions.bzl", "oci")
oci.pull(
    name = "svetoch_bazel_lib_argocd",
    #v3.5.2
    digest = "sha256:e2aadfae709d904e87f46ba4aa49601d827b3022db22cd4d03aae816a2e7097b",
    image = "quay.io/argoproj/argocd",
    platforms = [
        "linux/amd64",
    ],
)
oci.pull(
    name = "svetoch_bazel_lib_postgres-exporter",
    #v0.18.1
    digest = "sha256:fb96c4413985d4b23ab02b19022b3d70a86c8e0a62f41ab15ebb6f4673781a5d",
    image = "quay.io/prometheuscommunity/postgres-exporter",
    platforms = [
        "linux/amd64",
        "linux/arm64",
    ],
)
oci.pull(
    name = "svetoch_bazel_lib_spilo17",
    #spilo-17:4.0-p3
    digest = "sha256:17bf371c924196e4671f19d129fa86a80f7dcea7b2666cedca955ec0fba0b72b",
    image = "ghcr.io/zalando/spilo-17",
    platforms = [
        "linux/amd64",
    ],
)
use_repo(
    oci,
    "svetoch_bazel_lib_argocd",
    "svetoch_bazel_lib_argocd_linux_amd64",
    "svetoch_bazel_lib_postgres-exporter",
    "svetoch_bazel_lib_postgres-exporter_linux_amd64",
    "svetoch_bazel_lib_postgres-exporter_linux_arm64",
    "svetoch_bazel_lib_spilo17",
    "svetoch_bazel_lib_spilo17_linux_amd64",
)

apt = use_extension("@rules_distroless//apt:extensions.bzl", "apt")

#bazel run @svetoch_bazel_lib_trixie//:lock
apt.install(
    name = "svetoch_bazel_lib_trixie",
    lock = "@svetoch_bazel_lib//deps/deb:trixie.lock.json",
    manifest = "@svetoch_bazel_lib//deps/deb:trixie.yaml",
)
use_repo(apt, "svetoch_bazel_lib_trixie")

http_archive(
    name = "svetoch_bazel_lib_ca_certificates",
    build_file_content = "exports_files([\"data.tar.xz\"])",
    sha256 = "3269df8178f5402093a57c754810f8ce59e1a0cf9361aa72252bf3186cfc32d7",
    type = ".deb",
    urls = ["https://snapshot.debian.org/archive/debian/20260706T142243Z/pool/main/c/ca-certificates/ca-certificates_20260601_all.deb"],
)

http_file(
    name = "svetoch_bazel_lib_bazelisk",
    downloaded_file_path = "bazelisk",
    sha256 = "22e7d3a188699982f661cf4687137ee52d1f24fec1ec893d91a6c4d791a75de8",
    url = "https://github.com/bazelbuild/bazelisk/releases/download/v1.28.1/bazelisk-linux-amd64",
)

http_file(
    name = "svetoch_bazel_lib_yc_cli",
    downloaded_file_path = "yc",
    sha256 = "6980db14cfb975e1068d23a3440a5c4617019d9d66316659aaacfec47ab2466c",
    url = "https://storage.yandexcloud.net/yandexcloud-yc/release/1.31.0/linux/amd64/yc",
)

http_archive(
    name = "svetoch_bazel_lib_docker_credential_gcr",
    build_file_content = "exports_files([\"docker-credential-gcr\"])",
    sha256 = "fc8927596b8b2ac939a48b020bd1105dff8c367f584a2b3b54c08915127c9ebb",
    urls = ["https://github.com/GoogleCloudPlatform/docker-credential-gcr/releases/download/v2.1.32/docker-credential-gcr_linux_amd64-2.1.32.tar.gz"],
)

##################
# Python support
##################
bazel_dep(name = "aspect_rules_py", version = "1.3.2")
bazel_dep(name = "rules_python", version = "1.2.0")

python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(
    python_version = "3.11",
)
use_repo(python, python = "python_versions")

pip = use_extension("@rules_python//python/extensions:pip.bzl", "pip")
pip.parse(
    hub_name = "svetoch_bazel_lib_py_deps",
    python_version = "3.11",
    requirements_lock = "@svetoch_bazel_lib//deps/py:requirements_lock_3_11.txt",
)
use_repo(pip, "svetoch_bazel_lib_py_deps")
